import { Doctor } from "./type";

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Roda Khatib",
    specialty: "Pediatric Surgery",
    location: "Dokki and Mohandessin",
    rating: 4.8,
    image: "https://i.pravatar.cc/300?img=12",
  },
  {
    id: 2,
    name: "Tala Samani",
    specialty: "ENT",
    location: "New Cairo, Revolution Street",
    rating: 4.5,
    image: "https://i.pravatar.cc/300?img=32",
  },
  {
    id: 3,
    name: "Tamer Yehia",
    specialty: "Bones",
    location: "Dokki and Mohandessin",
    rating: 4.3,
    image: "https://i.pravatar.cc/300?img=27",
  },
  {
    id: 4,
    name: "Nahia Radwan",
    specialty: "Psychiatric",
    location: "Maadi, Ring Road",
    rating: 4.9,
    image: "https://i.pravatar.cc/300?img=48",
  },
  {
    id: 5,
    name: "Omar Radwani",
    specialty: "Teeth",
    location: "Nasr City, Makram Street",
    rating: 4.6,
    image: "https://i.pravatar.cc/300?img=9",
  },
  {
    id: 6,
    name: "Ahmed Masoud",
    specialty: "Teeth",
    location: "Nasr City, Youssef Abbas",
    rating: 4.7,
    image: "https://i.pravatar.cc/300?img=65",
  },
  {
    id: 7,
    name: "Mohamed Roshwan",
    specialty: "Kidney",
    location: "Nasr City, Aviation Street",
    rating: 4.7,
    image: "https://i.pravatar.cc/300?img=28",
  },
  {
    id: 8,
    name: "Hager Abdalla",
    specialty: "Nutrition and Dietetics",
    location: "Sheikh Zayed, SODIC",
    rating: 4.8,
    image: "https://i.pravatar.cc/300?img=42",
  },
  {
    id: 9,
    name: "Mohamed Hatem",
    specialty: "Vascular Surgery",
    location: "New Cairo, Mostafa El-Nahhas",
    rating: 4.7,
    image: "https://i.pravatar.cc/300?img=52",
  },
  {
    id: 10,
    name: "Ahmed Muslim",
    specialty: "Rheumatism",
    location: "Nasr City, Mostafa El-Nahhas",
    rating: 4.7,
    image: "https://i.pravatar.cc/300?img=44",
  },
  {
    id: 11,
    name: "Ahmed Tayeb",
    specialty: "Digestive and Endoscopic Surgery",
    location: "Dokki and Mohandessin",
    rating: 4.7,
    image: "https://i.pravatar.cc/300?img=56",
  },
  {
    id: 12,
    name: "Mohamed Al-Khatib",
    specialty: "Teeth",
    location: "Pyramids Gardens",
    rating: 4.3,
    image: "https://i.pravatar.cc/300?img=58",
  },
];
